config/routes.rb
Rails.application.routes.draw do  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles
  resources :projects
  resources :toys
  resources :nfts

  match "/art/series/:series" => "arts#series", via: :get, as: 'series_art'
  resources :arts, :path => "art"

  get 'health', to: 'pages#health'
  get 'interviews', to: 'pages#interviews'
  get 'music', to: 'pages#music'
  get 'now', to: 'pages#now'
  get 'podcasts', to: 'pages#podcasts'
  get 'reading', to: 'pages#reading'
  get 'learning', to: 'pages#learning'
  get 'gear', to: 'pages#gear'
  get 'investments', to: 'pages#investments'

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  has_many_attached :images
  belongs_to :art_category

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/art_category.rb
class ArtCategory < ApplicationRecord
  has_many :arts

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/nft.rb
class Nft < ApplicationRecord
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many_attached :images

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order('publish_at desc')

    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @article = Article.find_by(slug: params[:id])
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @art = Art.all.order(Arel.sql('RANDOM()'))
    @categories = ArtCategory.all.order(:name)
  end

  def show
    @art = Art.find(params[:id])
  end

  def series
    @series = ArtCategory.where(slug: params[:series]).first
    @art = @series.arts.order(Arel.sql('RANDOM()'))
  end
  
end

app/controllers/nfts_controller.rb
class NftsController < ApplicationController
  def index
    @nfts = Nft.all.order(:collection_name, :asset_name).where(hidden: false).where.not(asset_image_url: nil)
  end

  def show
    @nft = Nft.find_by(slug: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def gear
  end

  def index
  end

  def interviews
  end

  def music
  end

  def now
  end

  def podcasts
  end

  def reading
  end

  def investments
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order('year ASC, id ASC')
  end

  def show
    @project = Project.find_by(slug: params[:id])
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all.order(:platform, :name)
  end

  def show
    @toy = Toy.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      #link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end

  def meta_image(meta_image)
    content_for(:meta_image) { meta_image }
  end

  def last_updated
    last_updated = Rails.cache.fetch('last_updated', expires_in: 12.hours) do
      response = HTTParty.get('https://api.github.com/repos/Shpigford/joshpigford.com')
      json = JSON.parse(response.body)
      json['pushed_at']
    end
    last_updated.present? ? last_updated : Time.now
  end
end

app/helpers/art_helper.rb
module ArtHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/nfts_helper.rb
module NftsHelper
  def nft_image(url)
    if url.include?('ipfs:')
      token = url.gsub('ipfs://','')
      #"https://cloudflare-ipfs.com/ipfs/#{token}/"
      "https://fxparty.mypinata.cloud/ipfs/#{token}"
    else
      url
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rouge/renderer.rb
require 'redcarpet'
require 'rouge'
# require 'rouge/plugins/redcarpet'
require_dependency 'rouge/plugins/redcarpet'

class Rouge::Renderer < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/articles/index.html.erb
<%- 
  title "Articles"
  description "A collection of fine writing by Josh Pigford" 
-%>

<div class="prose max-w-none">
  <h1>Articles</h1>

  <ul>
  <% @articles.each do |article| %>
     <li>
      <%= link_to article.title, article_path(article.slug) %> <time><%= article.publish_at.strftime('%B %e, %Y') %></time></li>
  <% end %>
  </ul>
</div>

app/views/articles/show.html.erb
<%- 
  title @article.title
  description "#{markdown(@article.body).gsub(%r{</?[^>]+?>}, '')[0...300]}..." 
-%>

<div class="prose">
  <article class="h-entry">
    <h1 class="mb-0"><span class="p-name"><%= @article.title %></span> <a href="<%= article_url(@article.slug) %>" class="published u-url"></a></h1>
    <time class="font-bold dt-published" datetime="<%= @article.publish_at.iso8601 %>"><%= @article.publish_at.strftime('%B %e, %Y') %></time>
    <div class="e-content">
      <%= markdown(@article.body) %>
    </div>
  </article>
</div>

app/views/arts/index.html.erb
<%- 
  title "Art"
  description "Art by Josh Pigford" 
-%>

<div class="prose max-w-none">
  <h1>Art</h1>

  <p>
    series: 
    <% @categories.order(:name).each do |cat| %>
      <%= link_to cat.name, series_art_path(cat.slug) %><%= "," if cat != @categories.last %>
    <% end %>
  </p>

  <div class="not-prose">
    <div class="gap-3 mx-auto space-y-3 columns-5">
      <% @art.each do |art| %>
      <div class="break-inside-avoid">
        <%= link_to art_path(art) do %>
        <%= image_tag url_for(art.images.first.variant(resize_to_limit: [500, 800])), class: 'rounded-lg shadow-lg' %>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/arts/series.html.erb
<%- 
  title "#{@series.name} - Art"
  description "The #{@series.name} series of art by Josh Pigford" 
-%>

<p class="breadcrumb"><%= link_to "Art", arts_path %> &rarr; </p>
<div class="prose max-w-none">
  <h1><%=@series.name %></h1>

  <div class="not-prose">
    <div class="gap-3 mx-auto space-y-3 columns-5">
      <% @art.each do |art| %>
      <div class="break-inside-avoid">
        <%= link_to art_path(art) do %>
        <%= image_tag url_for(art.images.first.variant(resize_to_limit: [500, 800])), class: 'rounded-lg shadow-lg' %>
        <% end %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/arts/show.html.erb
<%- 
  title "#{@art.name} - #{@art.art_category.name} - Art"
  description "#{@art.name} from the #{@art.art_category.name} series of art by Josh Pigford"
  meta_image rails_representation_url(@art.images.first.variant(resize_to_fill: [1200, 800]))
-%>

<p class="breadcrumb"><%= link_to "Art", arts_path %> &rarr; <%= link_to @art.art_category.name, series_art_path(@art.art_category.slug) %> &rarr; </p>
<div class="prose max-w-none">
<h1><%= @art.name %></h1>
<div class="grid items-start grid-cols-2">
  <div class="not-prose">
    <p class="mt-0 mr-8"><%= image_tag url_for(@art.images.first.variant(resize_to_limit: [1200, 1200])), class: 'rounded-lg shadow-lg' %></p>
  </div>
  <table>
    <tr> 
      <th>Series</th>
      <td><%= @art.art_category.name %></td>
    </tr>
    <tr> 
      <th>Created</th>
      <td>
      <% if @art.produced_on.present? %>
        <%= @art.produced_on.strftime('%b %-d, %Y') %>
      <% else %>
        <%= @art.created_at.strftime('%b %-d, %Y') %>
      <% end %>
      </td>
    </tr>
    <% if @art.description.present? %>
    <tr> 
      <th>Description</th>
      <td><%= @art.description %></td>
    </tr>
    <% end %>
    <% if @art.tools.present? %>
    <tr> 
      <th>Tools</th>
      <td><%= @art.tools %></td>
    </tr>
    <% end %>
    <% if @art.nft == true %>
    <tr> 
      <th>NFT</th>
      <td><%= link_to "Purchase", @art.external_link %></td>
    </tr>
    <% else %>
    <tr> 
      <th>Download</th>
      <td><%= link_to "Full Size", rails_representation_url(@art.images.first.variant(resize_to_limit: [5000, 5000])) %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>

app/views/nfts/index.html.erb
<%- 
  title "NFTs"
  description "NFTs owned by Josh Pigford"
-%>

<div class="prose max-w-none">
  <h1>NFTs</h1>
  <p>I dove down the NFT rabbit hole starting in early 2021. Here's my collection across both ETH and XTZ!</p>

  <div class="not-prose">
  <ul role="list" class="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
    <% @nfts.each do |nft| %>
    <li class="relative">
      <%= link_to nft_path(nft.slug) do %>
      <div class="block w-full overflow-hidden bg-gray-100 rounded-lg shadow-lg group aspect-w-1 aspect-h-1 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500">
        <%= image_tag nft_image(nft.asset_image_url), class: 'object-cover pointer-events-none group-hover:opacity-75' %>
      </div>
      <p class="block mt-2 text-sm font-medium text-gray-900 truncate pointer-events-none"><%= nft.asset_name %></p>
      <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= nft.collection_name %></p>
      <% end %>
    </li>
  <% end %>
    </ul>
  </div>
</div>

app/views/nfts/show.html.erb
<%- 
  title "#{@nft.asset_name} - #{@nft.collection_name} - NFTs"
  description "NFTs owned by Josh Pigford"
  meta_image nft_image(@nft.asset_image_url)
-%>

<p class="breadcrumb"><%= link_to "NFTs", nfts_path %> &rarr; </p>
<div class="prose max-w-none">
<h1><%= @nft.asset_name %></h1>
<div class="grid items-start grid-cols-2">
  <div class="not-prose">
    <p class="mt-0 mr-8"><%= image_tag nft_image(@nft.asset_image_url), class: 'shadow-lg rounded-lg' %></p>
  </div>
  <table>
    <tr> 
      <th>Network</th>
      <td><%= @nft.network %></td>
    </tr>
    <% if @nft.collection_name.present? %>
    <tr> 
      <th>Collection</th>
      <td><%= @nft.collection_name %></td>
    </tr>
    <% end %>
    <% if @nft.network == 'ETH' %>
    <tr> 
      <th>External Link</th>
      <td><%= link_to "View on OpenSea", @nft.external_link %></td>
    </tr>
    <% end %>
    <% if @nft.description.present? %>
    <tr> 
      <th>Description</th>
      <td><%= simple_format(@nft.description) %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>

app/views/projects/index.html.erb
<%- 
  title "Projects"
  description "I've worked on (and continue to work on) an absurd number of things. Current tally? #{@projects.count} projects."
-%>

<div class="prose max-w-none">
  <h1>Projects</h1>
  <p>I've worked on (and continue to work on) an absurd number of things. Current tally? <b><%=@projects.count %> projects</b>.</p>

  <table class="project_list">
    <thead>
      <tr>
        <th>Project</th>
        <th>Started</th>
        <th>Description</th>
        <th>What Happened</th>
      </tr>
    </thead>
    <tbody class="text-sm">
      <% @projects.each do |project| %>
      <tr class="group odd:bg-white even:bg-gray-100 hover:bg-blue-700">
        <td class="px-2 py-3"><%= link_to project.name, project_path(project.slug), class: 'block group-hover:text-white' %></td>
        <td><%= link_to project.year, project_path(project.slug), class: 'block group-hover:text-white' %></td>
        <td><%= link_to project.description, project_path(project.slug), class: 'block group-hover:text-white' %></td>
        <td><%= link_to project.outcome, project_path(project.slug), class: 'block group-hover:text-white' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/projects/show.html.erb
<%- 
  title "#{@project.name} - Projects"
  description "#{@project.name}: #{@project.description}"
-%>

<div class="prose">
  <p class="breadcrumb"><%= link_to "&larr; Back to projects".html_safe, projects_path %></p>
  <h1><%= @project.name %> <time><%= @project.year %></time></h1>
  <p><%= @project.description %></p>

  <h3>What happened?</h3>
  <p><%= @project.outcome %></p>

  <% if @project.notes.present? %>
  <h3>Interesting bits</h3>
  <p><%= @project.notes %></p>
  <% end %>

  <% if @project.link.present? %>
  <h3><%= link_to "Go Wayback &rarr;".html_safe, @project.link %></h3>
  <% end %>
</div>

app/views/toys/index.html.erb
<%- 
  title "Designer Toys"
  description "I started collecting designer toys back in 2004. Eventually, my little hobby turned into an actual toy store that my wife and I started in 2006, and then sold in 2009. My collection isn't quite what it was back then, but in the past few years I've started actively collecting again. This is a place for me to show off that collection!"
-%>

<div class="prose max-w-none">
  <h1>Designer Toys</h1>
  <p>I started collecting designer toys back in 2004. Eventually, my little hobby turned into an <a href="https://joshpigford.com/projects/fugitive-toys">actual toy store</a> that my wife and I started in 2006, and then sold in 2009. My collection isn't quite what it was back then, but in the past few years I've started actively collecting again. This is a place for me to show off that collection!</p>

  <div class="not-prose">
  <ul role="list" class="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
    <% @toys.each do |toy| %>
    <li class="relative">
      <%= link_to toy_path(toy) do %>
      <div class="block w-full overflow-hidden bg-gray-100 rounded-lg shadow-lg group aspect-w-1 aspect-h-1 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500">
        <%= image_tag url_for(toy.images.first.variant(resize_and_pad: [500, 500, background: [255]])), class: 'object-cover pointer-events-none group-hover:opacity-75' %>
      </div>
      <p class="block mt-2 text-sm font-medium text-gray-900 truncate pointer-events-none"><%= toy.name %></p>
      <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= toy.platform %></p>
      <% end %>
    </li>
  <% end %>
    </ul>
  </div>
</div>

app/views/toys/show.html.erb
<%- 
  title "#{@toy.name} - #{@toy.platform} - Designer Toys"
  description "#{@toy.name} by #{@toy.artist}, from Josh Pigford's designer toy collection."
  meta_image rails_representation_url(@toy.images.first.variant(resize_to_fill: [1200, 800]))
-%>

<p class="breadcrumb"><%= link_to "Toys", toys_path %> &rarr; </p>
<div class="prose max-w-none">
<h1><%= @toy.name %></h1>
<div class="flex items-start">
  <div class="flex-1">
    <% @toy.images.each do |image| %>
      <p><%= image_tag url_for(image.variant(resize_to_limit: [800, 800])) %></p>
    <% end %>
  </div>
  <table class="flex-1">
    <tr> 
      <th>Artist</th>
      <td><%= @toy.artist %></td>
    </tr>
    <tr> 
      <th>Manufacturer</th>
      <td><%= @toy.manufacturer %></td>
    </tr>
    <tr> 
      <th>Platform</th>
      <td><%= @toy.platform %></td>
    </tr>
    <% if @toy.series.present? %>
    <tr> 
      <th>Series</th>
      <td><%= @toy.series %></td>
    </tr>
    <% end %>
    <tr> 
      <th>Size</th>
      <td><%= @toy.size %>"</td>
    </tr>
    <tr> 
      <th>Color</th>
      <td><%= @toy.color %></td>
    </tr>
    <tr> 
      <th>Released</th>
      <td><%= @toy.release_date.strftime('%Y') %></td>
    </tr>
    <% if @toy.original_price.present? %>
    <tr> 
      <th>Original Price</th>
      <td><%= @toy.original_price %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>