config/routes.rb
Rails.application.routes.draw do  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :articles
  resources :projects
  resources :toys
  resources :nfts

  match "/art/series/:series" => "arts#series", via: :get, as: 'series_art'
  resources :arts, :path => "art"

  get 'health', to: 'pages#health'
  get 'interviews', to: 'pages#interviews'
  get 'music', to: 'pages#music'
  get 'now', to: 'pages#now'
  get 'podcasts', to: 'pages#podcasts'
  get 'reading', to: 'pages#reading'
  get 'learning', to: 'pages#learning'
  get 'gear', to: 'pages#gear'
  get 'investments', to: 'pages#investments'

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  has_many_attached :images
  belongs_to :art_category

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/art_category.rb
class ArtCategory < ApplicationRecord
  has_many :arts

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/nft.rb
class Nft < ApplicationRecord
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many_attached :images

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order('publish_at desc')

    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @article = Article.find_by(slug: params[:id])
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index
    @art = Art.all.order(Arel.sql('RANDOM()'))
    @categories = ArtCategory.all.order(:name)
  end

  def show
    @art = Art.find(params[:id])
  end

  def series
    @series = ArtCategory.where(slug: params[:series]).first
    @art = @series.arts.order(Arel.sql('RANDOM()'))
  end
  
end

app/controllers/nfts_controller.rb
class NftsController < ApplicationController
  def index
    @nfts = Nft.all.order(:collection_name, :asset_name).where(hidden: false).where.not(asset_image_url: nil)
  end

  def show
    @nft = Nft.find_by(slug: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def gear
  end

  def index
  end

  def interviews
  end

  def music
  end

  def now
  end

  def podcasts
  end

  def reading
  end

  def investments
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all.order(:platform, :name)
  end

  def show
    @toy = Toy.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      #link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end

  def meta_image(meta_image)
    content_for(:meta_image) { meta_image }
  end

  def last_updated
    last_updated = Rails.cache.fetch('last_updated', expires_in: 12.hours) do
      response = HTTParty.get('https://api.github.com/repos/Shpigford/joshpigford.com')
      json = JSON.parse(response.body)
      json['pushed_at']
    end
    last_updated.present? ? last_updated : Time.now
  end
end

app/helpers/art_helper.rb
module ArtHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/nfts_helper.rb
module NftsHelper
  def nft_image(url)
    if url.include?('ipfs:')
      token = url.gsub('ipfs://','')
      #"https://cloudflare-ipfs.com/ipfs/#{token}/"
      "https://fxparty.mypinata.cloud/ipfs/#{token}"
    else
      url
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta name="title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta name="description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Maker. Dabbler. Founder and CEO of Maybe." %>">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta property="og:description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Maker. Dabbler. Founder and CEO of Maybe." %>">
    <meta property="og:image" content="<%= image_url(content_for?(:meta_image) ? yield(:meta_image) : "meta.jpg") %>">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta property="twitter:description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Maker. Dabbler. Founder and CEO of Maybe." %>">
    <meta property="twitter:image" content="<%= image_url(content_for?(:meta_image) ? yield(:meta_image) : "meta.jpg") %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b829d8d3c1.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="lowercase">
    <header class="flex mb-10">
      <div class="flex-none mr-8">
        <%= link_to image_tag("headshot-collage.jpg", alt: 'Josh Pigford', class: 'w-36 h-36 rounded-full'), root_path %>
      </div>
      <div class="flex-auto mt-3">
        <h1 class="mb-3 text-3xl font-black"><%= link_to "Josh Pigford", root_path, class: 'text-black', rel: 'me' %> <span><a href="https://twitter.com/Shpigford" rel="me" class="text-black hover:bg-transparent hover:text-blue-700"><i class="text-2xl fab fa-twitter"></i></a></span></h1>
        <p class="mb-4">Maker. Dabbler. I can't stop starting things. Bearded.</p>
        <p class="font-bold">&rarr;
          <%= link_to 'Art', arts_path %>, <%= link_to 'Articles', articles_path %>, <%= link_to 'Investments', investments_path %>, <%= link_to 'Interviews', interviews_path %>, <%= link_to 'Music', music_path %>, <%= link_to 'Now', now_path %>, <%= link_to 'Projects', projects_path %>, <%= link_to 'Podcasts', podcasts_path %>, <%= link_to 'Reading', reading_path %>, <%= link_to 'Gear', gear_path %>, <%= link_to 'Toys', toys_path %>, <%= link_to 'NFTs', nfts_path %>
        </p>
      </div>
    </header>
    
    <main>
      <%= yield %>
    </main>

    <footer class="mt-20 text-sm text-gray-400">
      Site last updated on <b><%= last_updated.to_datetime.in_time_zone('Central Time (US & Canada)').strftime('%B %e, %Y at %l:%M%P %Z') %></b>. <a href="https://github.com/Shpigford/joshpigford.com/commits/main">Changelog</a>.
    </footer>

    <script src="https://cdn.usefathom.com/3.js" site="PKXZNVYB"></script>
  </body>
</html>

app/views/pages/gear.html.erb
<%- 
  title "Gear"
  description "Most of the gear I use regularly to make all the things!"
-%>

<div class="prose max-w-none">
  <h1>Gear</h1>
  <p>Here's most of the things I use regularly to make all the things!</p>

  <h2>Apple</h2>
  <p>These warrant their own category...for better or worse!</p>
  <ul>
    <li><a href="https://www.apple.com/macbook-pro/">MacBook Pro (13-inch, M1, 2020)</a></li>
    <li><a href="https://www.apple.com/ipad-pro/">iPad Pro (11-inch)</a></li>
    <li><a href="https://www.apple.com/apple-pencil/">Apple Pencil</a></li>
    <li><a href="https://www.apple.com/iphone-13-pro/">iPhone 13 Pro</a></li>
    <li><a href="https://www.apple.com/airpods-pro/">AirPods Pro</a></li>
  </ul>

  <h2>Audio/Video/Podcasting</h2>
  <p>These are things I use primarily for podcasting, but also for some hobby electronic music creation.</p>
  <ul>
    <li><a href="https://dbxpro.com/en/products/286s">DBX 286S Preamp</a></li>
    <li><a href="https://www.m-audio.com/products/view/studiophile-av-40">M-Audio Studiophile AV 40 Studio Monitors</a></li>
    <li><a href="https://www.behringer.com/Categories/Behringer/Computer-Audio/Interfaces/UMC404HD/p/P0BK1">Behringer U-Phoria UMC404HD Audio Interface</a></li>
    <li><a href="https://www.logitech.com/en-us/product/hd-pro-webcam-c920s">Logitech C920</a></li>
    <li><a href="https://www.audio-technica.com/cms/wired_mics/b8dd84773f83092c/index.html">Audio-Technica ATR2100-USB</a></li>
    <li><a href="https://www.akaipro.com/mpk-mini-mkii">Akai MPK Mini MKII MIDI Keyboard</a></li>
    <li><a href="https://www.audio-technica.com/cms/headphones/75b2f282c93a7651/index.html">Audio-Technica ATH-M40x Headphones</a></li>
  </ul>

  <h2>Maker</h2>
  <p>The tools I use to design, prototype and produce physical products!</p>
  <ul>
    <li><a href="https://glowforge.us/r/JTTLXZSA">Glowforge Plus</a></li>
    <li><a href="https://www.creality3d.shop/products/creality-cr-10s-diy-desktop-3d-printer-300x300x400mm">Creality CR-10S</a></li>
    <li><a href="https://www.inventables.com/technologies/x-carve">X-Carve</a></li>
  </ul>

  <h2>Software</h2>
  <p>Apps I use just about every day.</p>
  <ul>
    <li><a href="https://1password.com">1Password</a></li>
    <li><a href="https://www.adobe.com/creativecloud.html">Adobe Creative Cloud</a></li>
    <li><a href="https://getcleanshot.com">CleanShot</a></li>
    <li><a href="https://deepnest.io">Deepnest</a></li>
    <li><a href="https://www.dropbox.com">Dropbox</a></li>
    <li><a href="https://www.figma.com">Figma</a></li>
    <li><a href="https://www.autodesk.com/products/fusion-360/overview">Fusion 360</a></li>
    <li><a href="https://www.notion.so">Notion</a></li>
    <li><a href="https://www.simplify3d.com">Simplify3D</a></li>
    <li><a href="https://www.sketch.com">Sketch</a></li>
    <li><a href="https://slack.com">Slack</a></li>
    <li><a href="https://soulver.app">Soulver</a></li>
    <li><a href="https://www.sublimetext.com">Sublime Text</a></li>
    <li><a href="https://superhuman.com">Superhuman</a></li>
    <li><a href="https://culturedcode.com/things/">Things</a></li>
    <li><a href="https://trello.com">Trello</a></li>
    <li><a href="https://zoom.us">Zoom</a></li>
  </ul>
</div>

app/views/pages/health.html.erb
<h1>Health</h1>
<p>In 2020 I'm focusing on living a healthier and more sustainable lifestyle. I've always struggled with getting regular exercise as well as having a healthy weight.</p>
<p>I trained for and ran a marathon in 2019 and now I'm working on losing 50 pounds along with training for another marathon in late 2020. 🎉</p>

<h3>Weight Loss</h3>
<p>As of January 1, 2019, I'm 231 pounds with 30% body fat. At 6' 1", those numbers mean I'm considered obese.</p> 

<p>I'm following the slow carb diet (<a href="https://tim.blog/2012/07/12/how-to-lose-100-pounds/">as popularized by Tim Ferris</a>) and my goal weight is 180 pounds with 20% body fat.</p>

<h4>Weight Loss Progress</h4>
<p>
  <%= image_tag 'weighin_jan9.png', class: 'graph' %>
</p>

<h3>Marathon</h3>
<p>On April 28, 2019, I <a href="https://www.strava.com/activities/2326490991">ran a marathon</a>! It was brutal, but I'm really proud of myself for completing it.</p>

app/views/pages/index.html.erb
<div class="prose max-w-none">
  <h2 class="mb-2">What I'm working on</h2>
  <p>In 2021 I founded <a href="https://maybe.co">Maybe</a> where we're helping folks take control of their financial future. I also run <a href="https://lasertweets.co">Laser Tweets</a> because we all need something ridiculous to do.</p>

  <hr>

  <h2 class="mb-2">Interviews</h2>
  <p>Over the years I've <a href="/interviews">done some 40+ interviews</a>, mostly about business.</p>

  <hr>

  <h2 class="mb-2">Past projects</h2>
  <p>I've been a professional maker of things for 15+ years. <a href="/projects">See a thorough list of everything I've ever made &rarr;</a></p>

  <hr>

  <h2 class="mb-2">Music</h2>
  <p>I listen to an absurd amount of music. Basically I've always got <em>something</em> playing. <a href="/music">Check out what I'm listening to</a> along with some curated lists.</p>

  <hr>

  <h2 class="mb-2">Podcasts</h2>
  <p>I listen to way too many podcasts. <a href="/podcasts">See what I'm listening to</a> so you can also listen to way too many podcasts.</p>

  <hr>

  <h2 class="mb-2">Get in touch</h2>
  <p>I try to stay pretty accessible, but it may take a week or two to respond. Best ways to get in touch are on Twitter at <a href="http://twitter.com/Shpigford" rel="me">@Shpigford</a> or via email at <a href="mailto:josh@joshpigford.com" rel="me">josh@joshpigford.com</a>.</p>
</div>

app/views/pages/interviews.html.erb
<%- 
  title "Interviews"
  description "Interviews with Josh Pigford"
-%>

<div class="prose max-w-none">
  <h1>Interviews</h1>
  <ul>
    <li><a href="https://www.startupsfortherestofus.com/episodes/episode-534-a-4m-exit-with-josh-pigford-of-baremetrics">Startups for the Rest of Us</a> <time datetime="2021-02-02">Feb 2, 2021</time></li>
    <li><a href="https://saas.transistor.fm/episodes/how-coronavirus-is-impacting-software-companies">Build Your SaaS</a> <time datetime="2020-04-14">Apr 14, 2020</time></li>
    <li><a href="https://anchor.fm/theproductbusiness/episodes/19--Josh-Pigford---Almost-selling-Baremetrics-for-5m-eaf8b2">The Product Business</a> <time datetime="2020-01-27">Jan 27, 2020</time></li>
    <li><a href="https://anchor.fm/hypertribal/episodes/2---Josh-Pigford--Founder-of-Baremetrics-e2uabe/a-a120ajp">First Customers</a> <time datetime="2019-12-18">Dec 18, 2019</time></li>
    <li><a href="https://www.gvkhna.com/blog/2019-12-13-podcast-ep4-josh-pigford-founder-at-baremetrics/">Founder Stories</a> <time datetime="2019-12-13">Dec 13, 2019</time></li>
    <li><a href="https://trackly.com/podcast/hiring-a-remote-team-of-all-starts-with-josh-pigford">Trackly</a> <time datetime="2018-10-08">Oct 8, 2018</time></li>
    <li><a href="https://www.foodbloggerpro.com/blog/article/josh-pigford/">Food Blogger Pro</a> <time datetime="2018-09-25">Sep 25, 2018</time></li>
    <li><a href="https://www.ryrob.com/baremetrics-josh-pigford/">The Side Hustle Project</a> <time datetime="2018-06-06">Jun 6, 2018</time></li>
    <li><a href="https://everyonehatesmarketers.com/61-josh-pigford-baremetrics/">Everyone Hates Marketers</a> <time datetime="2018-05-08">May 8, 2018</time></li>
    <li><a href="https://www.hrcoaching.com/sbh82/">HR Coaching</a> <time datetime="2018-04-03">Apr 3, 2018</time></li>
    <li><a href="https://www.getcredo.com/side-project-takes-josh-pigford-shpigford-baremetrics/">Credocast</a> <time datetime="2018-02-15">Feb 15, 2018</time></li>
    <li><a href="https://uibreakfast.com/89-saas-vs-ecommerce-josh-pigford/">UI Breakfast</a> <time datetime="2018-01-04">Jan 4, 2018</time></li>
    <li><a href="http://productizepodcast.com/35-josh-pigford-on-solo-founding-acquiring-many-skillsets/">Productize Podcast</a> <time datetime="2017-10-04">Oct 4, 2017</time></li>
    <li><a href="http://www.parentpreneur.com/podcast-010-josh-pigford-how-to-retain-customers-to-build-a-profitable-business/">Parentpreneur</a> <time datetime="2017-07-25">Jul 25, 2017</time></li>
    <li><a href="https://www.geckoboard.com/blog/secrets-for-scaling-josh-pigford-baremetrics-podcast/">Geckoboard: Secrets for Scaling</a> <time datetime="2017-07-05">Jul 5, 2017</time></li>
    <li><a href="https://www.startups.co/articles/josh-pigford-is-doing-the-unthinkable-startup-co-exclusive-interview">Startups.co</a> <time datetime="2017-04-25">Apr 25, 2017</time></li>
    <li><a href="http://www.startupsuccesspodcast.com/home/episode-38-josh-pigford">The Startup Success Podcast</a> <time datetime="2017-04-18">Apr 18, 2017</time></li>
    <li><a href="https://www.indiehackers.com/podcast/006-josh-pigford-of-baremetrics">Indie Hackers</a> <time datetime="2017-03-08">Mar 8, 2017</time></li>
    <li><a href="http://whatusersdo.com/blog/balancing-ux-cx-business/">WhatUsersDo</a> <time datetime="2017-02-14">Feb 14, 2017</time></li>
    <li><a href="https://soundcloud.com/content-marketing/how-to-bootstrap-your-business-with-content-marketing-featuring-josh-pigford">Unscripted Content Marketing Podcasts</a> <time datetime="2017-02-06">Feb 6, 2017</time></li>
    <li><a href="https://startsustain.fireside.fm/josh-pigford">Starting &amp; Sustaining</a> <time datetime="2017-01-15">Jan 15, 2017</time></li>
    <li><a href="https://blog.nomnom.it/interview-with-josh-pigford-ceo-and-founder-of-baremetrics-part-of-our-customer-obsessed-2c6f44f4e139">NomNom: Customer-Obsessed</a> <time datetime="2017-01-15">Jan 15, 2017</time></li>
    <li><a href="http://coschedule.com/blog/prioritize-marketing-projects-josh-pigford-baremetrics-acm-012/">The Actionable Content Marketing Podcast</a> <time datetime="2016-12-13">Dec 13, 2016</time></li>
    <li><a href="http://andybaldacci.com/podcast/josh-pigford-baremetrics/">The Early Stage Founder Show</a> <time datetime="2016-09-20">Sep 20, 2016</time></li>
    <li><a href="https://www.geckoboard.com/blog/secrets-for-scaling-proactive-customer-success-grow-baremetrics/">Geckoboard: Secrets for Scaling</a> <time datetime="2016-09-12">Sep 12, 2016</time></li>
    <li><a href="http://www.productpeople.tv/79">Product People</a> <time datetime="2016-06-21">Jun 21, 2016</time></li>
    <li><a href="http://www.fullstackradio.com/26">Full Stack Radio</a> <time datetime="2015-09-29">Sep 29, 2015</time></li>
    <li><a href="http://growthhackingpodcast.com/josh-pigford-from-0-to-10k-in-6-months-with-baremetrics/">Growth Hacking Podcast</a> <time datetime="2015-08-27">Aug 27, 2015</time></li>
    <li><a href="http://www.startupsfortherestofus.com/episodes/episode-244-competition-transparency-and-funding-with-baremetrics-founder-josh-pigford">Startups for the Rest of Us</a> <time datetime="2015-07-07">Jul 7, 2015</time></li>
    <li><a href="http://mastermindfinder.com/podcast/theboishow/joshpigford/">Box of Inspirations</a> <time datetime="2015-06-06">Jun 6, 2015</time></li>
    <li><a href="http://hacktheentrepreneur.com/podcast/josh-pigford/">Hack the Entrepreneur</a> <time datetime="2015-05-25">May 25, 2015</time></li>
    <li><a href="http://growtheverywhere.com/growth-everywhere-interview/josh-pigford-baremetrics/">Growth Everywhere</a> <time datetime="2015-04-20">Apr 20, 2015</time></li>
    <li><a href="http://www.conversionaid.com/podcast/josh-pigford-baremetrics2/">ConversionAid (Part 2)</a> <time datetime="2015-03-10">Mar 11, 2015</time></li>
    <li><a href="http://www.conversionaid.com/podcast/josh-pigford-baremetrics1/">ConversionAid (Part 1)</a> <time datetime="2015-03-10">Mar 10, 2015</time></li>
    <li><a href="https://recruitee.com/blog/the-art-of-remote-hiring-process-with-josh-pigford-baremetrics-recruitee-founders-talks/">Recruitee</a> <time datetime="2015-01-05">Jan 5, 2015</time></li>
    <li><a href="https://mattkremer.com/mk-006-josh-pigford-simplicity-copycats-killing-your-products/">Matt Kremer Podcast</a> <time datetime="2014-11-05">Nov 5, 2014</time></li>
    <li><a href="http://baxtalk.libsyn.com/bare-metrics-22kmth-in-saas-josh-pigford">Self Made Entrepreneurs</a> <time datetime="2014-10-31">Oct 31, 2014</time></li>
    <li><a href="http://mixergy.com/interviews/josh-pigford-baremetrics/">Mixergy</a> <time datetime="2014-10-29">Oct 29, 2014</time></li>
    <li><a href="http://www.reddit.com/r/Entrepreneur/comments/2kf2xt/i_bootstrapped_a_saas_business_from_idea_to/">Reddit AMA</a> <time datetime="2014-10-27">Oct 27, 2014</time></li>
    <li><a href="http://hacktostart.com/josh-pigford/">Hack To Start</a> <time datetime="2014-10-06">Oct 6, 2014</time></li>
    <li><a href="http://www.entrepreneuronfire.com/podcast/joshpigford/">Entrepreneur On Fire</a> <time datetime="2014-09-07">Sep 7, 2014</time></li>
    <li><a href="http://www.successharbor.com/baremetrics-ceo-josh-pigford-shares-entrepreneur-story">Success Harbor</a> <time datetime="2014-08-04">Aug 4, 2014</time></li>
    <li><a href="http://thefoundation.com/podcast/episode59/">Starting From Nothing</a> <time datetime="2014-06-30">Jun 30, 2014</time></li>
    <li><a href="https://yourfirstcustomers.com/josh-pigford-baremetrics/">Your First Customers</a> <time datetime="2014-06-19">Jun 19, 2014</time></li>
    <li><a href="http://curaytor.com/baremetrics-audio">Curaytor Water Cooler</a> <time datetime="2014-06-18">Jun 18, 2014</time></li>
    <li><a href="http://www.chasingproduct.com/episodes/episode-13-organic-product-development-wjosh-pigford">Chasing Product</a> <time datetime="2014-02-04">Feb 4, 2014</time></li>
    <li><a href="http://podcasts.thoughtbot.com/giantrobots/80">Giant Robots</a> <time datetime="2013-12-23">Dec 23, 2013</time></li>
    <li><a href="http://supportops.co/episode-25-josh-pigford/">Support Ops</a> <time datetime="2013-10-22">Oct 22, 2013</time></li>
    <li><a href="https://lessaccounting.com/blog/josh-pigford-deathray-powercast">Deathray Powercast</a> <time datetime="2013-08-22">Aug 22, 2013</time></li>
  </ul>
</div>

app/views/pages/learning.html.erb
<h1>Learning</h1>
<p>Here are resources for learning various things that I've picked up over the years.</p>

<h3 id="programming">Programming</h3>

<h3 id="design">Design</h3>

<h3 id="business">Business</h3>

<h3 id="electronics">Electronics</h3>

<h3 id="woodworking">Woodworking</h3>

app/views/pages/music.html.erb
<%- 
  title "Music"
  description "I'm an obsessive music listener and have been my whole life. I won't say I'm a music snob, but let's be honest, 95% of popular music these days is categerically some of the worst music ever created, but I digress 👴🏻."
-%>

<div class="prose max-w-none">
  <h1>Music</h1>
  <p>I'm an obsessive music listener and have been my whole life. I won't say I'm a music snob, but let's be honest, 95% of popular music these days is categerically some of the worst music ever created, but I digress 👴🏻.</p>
  <p>You can follow along with what I'm listening to <a href="https://music.apple.com/profile/Shpigford">on Apple Music</a>.</p>
</div>

app/views/pages/music_2018.html.erb
<% 
  @albums = [1424372189, 1343868318, 1312021964, 1422828208, 1432911048, 1396292262, 1435252315, 1348607884, 1435775511, 1380809549]
%>

<h1>Top Albums of 2018</h1>
<p>These were the albums I had on rotation the most. In hindsight looks like I had pretty polarizing listening habits, going back and forth between pop and hardcore. 🤷‍♂️</p>

<% @albums.each do |album| %>
  <iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="315" style="width:100%;max-width:340px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/us/album/<%= album %>?app=music&at=1001lruc"></iframe>
<% end %>

app/views/pages/music_2019.html.erb
<% 
  @albums = [1475151504, 1439239477, 1459197530, 1491270855, 1458152823, 1441326645, 1462445652, 1466310161, 1467442146, 1470142125, 1473599936, 1476932664, 1480411285, 1448775380, 1485463688]
%>

<h1>Top Albums of 2019</h1>
<p>These were the albums, released in 2019, that I had on rotation the most.</p>

<% @albums.each do |album| %>
  <iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="315" style="width:100%;max-width:340px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/us/album/<%= album %>?app=music&at=1001lruc"></iframe>
<% end %>